# Generated by Django 4.2.11 on 2024-06-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='featured_image',
        ),
    ]
