# Generated by Django 4.2.11 on 2024-06-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_booking_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='duration',
        ),
    ]
